### ISSUE TITLE
feedback to parameter evaluation 

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-json#138]
This issue has feedback to `issue102_evaPar`.

In 
https://github.com/lbl-srg/modelica-json/blob/a8adb38ee5064ed36e65bad45ac4853d78703acb/test/FromModelica/cdlEva/json/FromModelica.TestEvaluation_4.json#L590
`type` is not needed here I believe because there is already a `className` if I understand it correctly. If `className` is used, then it has the same structure as `Real`.

How does a tool know what value `Buildings.Controls.OBC.CDL.Types.SimpleController.PI` has? I don't see this information in https://github.com/lbl-srg/modelica-json/blob/issue102_evaPar/test/FromModelica/cdlEva/json/FromModelica.TestEvaluation_4.json

Also, please add a schema similar to https://github.com/lbl-srg/modelica-json/blob/issue102_evaPar/schema-CDL.json
for the mode with and without parameter evaluation. We can then review the structure with the json schema viewer.

**Comment by JayHuLBL** [comment]
For now, the `Buildings.Controls.OBC.CDL.Types.SimpleController.PI` itself is the value of the parameter `controllerType`. It did not further assign value to `Buildings.Controls.OBC.CDL.Types.SimpleController.PI`. 

To allow propagating the enumeration type parameter values, I proposed to add tag to all the items in `Buildings.Controls.OBC.CDL.Types`, like:
```
type SimpleController = enumeration(
    P "P controller",
    PI "PI controller",
    PD "PD controller",
    PID "PID controller")
```
to be:
```
type SimpleController = enumeration(
    P   "1 - P controller",
    PI  "2 - PI controller",
    PD  "3 - PD controller",
    PID "4 - PID controller")
```

and also change the propagation list for instance:
```
"value_propagation": {
      "freProTMix.controllerType": "Buildings.Controls.OBC.CDL.Types.SimpleController.PI",
      "freProTMix.k": "0.1",
       ...
```

to be like:
```
"value_propagation": [
{
  "name": "freProTMix.controllerType",
  "value": 2,
  "type": "Buildings.Controls.OBC.CDL.Types.SimpleController"
},
{
  "name": "freProTMix.k",
  "value": 0.1,
  "type": "Real"
},
...
```

**Comment by JayHuLBL** [comment]
@mwetter 
The value propagation list now has been changed as suggested. See [TestEvaluation_4.json](https://github.com/lbl-srg/modelica-json/blob/issue102_evaPar/test/FromModelica/cdlEva/json/FromModelica.TestEvaluation_4.json). I am also thinking if the "value" should be number rather than being stringified:
```
     {
        "name": "freProTMix.Ti",
        "value": "120",
        "type": "Real"
      },
```
should be:
```
     {
        "name": "freProTMix.Ti",
        "value": 120,
        "type": "Real"
      },
```
Also, the JSON schema has been updated to include the [`value_propagation`](https://github.com/lbl-srg/modelica-json/blob/8f7d5dd77cec039575d11dc401553bb17afcc4c6/schema-CDL.json#L1115) list.

**Comment by mwetter** [comment]
@JayHuLBL Having the value as a number won't work. Consider
```
      {
        "name": "freProTMix.controllerType",
        "value": "Buildings.Controls.OBC.CDL.Types.SimpleController.PI",
        "type": "Buildings.Controls.OBC.CDL.Types.SimpleController"
      },
      {
        "name": "freProTMix.k",
        "value": "0.1",
        "type": "Real"
      },
```
For `controllerType`, it must be a string. So you can either use a string for all, or use a type, such as
```
     "enumeration":{
        "name": "freProTMix.controllerType",
          "value": "Buildings.Controls.OBC.CDL.Types.SimpleController.PI",
          "type": "Buildings.Controls.OBC.CDL.Types.SimpleController"
      },
     "real": {
        "name": "freProTMix.k",
          "value": 0.1,
         "min": 0 /* if specified */
         ...
        }
```
Then, either a ```enumeration`` or a ``real``` must be present.
