### ISSUE TITLE
trailing '/' in modelicaFile variable in the json output

### ISSUE THREAD

**Issue by anandkp92** [lbl-srg/modelica-json#155]
when adding the `modelicaFile` object to the json output, if the input package is given as for example `model/`, then the `modelicaFile` value will be like `model//BaseClasses/CoilRegister.mo`, which should be `model/BaseClasses/CoilRegister.mo`

TODO: remove the `//`

**Comment by anandkp92** [comment]
`node app.js -f test/FromModelica/ -m modelica -o json`
and
`node app.js -f test/FromModelica -m modelica -o json `

produced different `modelicaFile` for files in that package.

**Comment by JayHuLBL** [comment]
closed through PR #156.
