### ISSUE TITLE
misssing replaceable prefix in simplified-json

### ISSUE THREAD

**Issue by anandkp92** [lbl-srg/modelica-json#159]
When converting from `raw-json` to simplified `json` output, the replaceable prefix is lost. Fix this by adding it as a `prefix`

**Comment by anandkp92** [comment]
@JayHuLBL this is this what I'm thinking. Is this correct? 

```
replaceable Buildings.Fluid.Sensors.TemperatureTwoPort TSup;
````
becomes: 

```
{
    "className": "Buildings.Fluid.Sensors.TemperatureTwoPort",
    "modifier": "replaceable",
    "name": "TSup"
}
```

**Comment by JayHuLBL** [comment]
@anandkp92 I think it would be better to become:
```
{
    "prefix": "replaceable",
    "className": "Buildings.Fluid.Sensors.TemperatureTwoPort",
    "name": "TSup"
}
```

**Comment by mwetter** [comment]
@anandkp92 : would this also cover constructs such as
```modelica
  replaceable model BoreFieldType=Fluid.Geothermal.Borefields.OneUTube
    constrainedby Fluid.Geothermal.Borefields.BaseClasses.PartialBorefield(
      redeclare package Medium=Medium,
      allowFlowReversal=allowFlowReversal,
      borFieDat=datBorFie,
      energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial)
    "Wall heat transfer"
    annotation (choicesAllMatching=true);
```
which is from `Buildings.Experimental.DHC.EnergyTransferStations.Combined.Generation5.Subsystems.Borefield`?

**Comment by anandkp92** [comment]
@mwetter I don't think that is covered as currently `subModels` are not being handled - we lose that model declaration completely.  However, I just ran the modelica-json tool for that model and 

`replaceable parameter Fluid.Geothermal.Borefields.Data.Borefield.Example datBorFie` (Line 14) becomes
```
      "parameters": [
          {
            "prefix": "replaceable",
            "className": "Fluid.Geothermal.Borefields.Data.Borefield.Example",
            "name": "datBorFie",
            "modifications": [
              {
                "name": "conDat",
                "value": "Buildings.Fluid.Geothermal.Borefields.Data.Configuration.Example()",
                "isFinal": false
              }
            ],
            "annotation": {
              "dialog": {
                "tab": "General",
                "group": "Parameters"
              }
           }
          },
```

**Comment by mwetter** [comment]
Thanks for the update. Then the translation is incomplete and translating it back to Modelica would give a different model (with different behavior). This will need to be added for the Modelica mode. In Linkage, we will make extensive use of `constrainedby`.

**Comment by anandkp92** [comment]
completed with [v1.0.0](https://github.com/lbl-srg/modelica-json/tree/v1.0.0)
