### ISSUE TITLE
Installation/Troubleshooting to be updated

### ISSUE THREAD

**Issue by karthikeyad-pnnl** [lbl-srg/modelica-json#181]
Hello,

I was trying to install the parser using the InstallOnWindows.bat batch file. I kept getting an error that said the path variable JAVA_HOME was not correctly defined, and the moParser.jar file was not generated. I kept trying to resolve it by fixing the path in my system path variables, but was unsuccessful. It was only upon inspecting the batch file that I realized the path variable was being set by it, and wasn't being read from the system. On fixing the path in the batch file, the installation worked correctly and the jar file was generated.

Please update the Windows installation instructions to include this step.

Thanks,
Karthik

**Comment by JayHuLBL** [comment]
@karthikeyad-pnnl Thanks! It has been updated.
