### ISSUE TITLE
FE • Refactor getJsons and getSimpleJson to return JS object

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-json#233]
This ticket is to refactor the following functions from `lib/parser.js` so they return an actual JS object with the parsed data.

⚠︎ This object is an array containing the data for ***all*** Modelica classes used by the Modelica file passed as argument — even if a class is not actually parsed during the current invocation.
 
- This avoids manipulating the data for a given class via read/write access to the file system `JSON.parse(fs.readFileSync(...))`.
- This is a first step towards generating a "flat Modelica" object for a given class. With the current workflow relying on JSON files on disk, we fundamentally lose the information about which class is used by a given class (i.e., results from parsing a given class).

#### `getJsons`

The function currently declares `const jsonData = []` and returns `jsonData` without never populating the array.

This ticket will populate `jsonData` so `getJsons` does not return an empty array.

#### `getSimpleJson`

The function returns either `null` or the absolute path of the Modelica file that is parsed — not including the absolute path of the classes instantiated in this file, which are only pushed to `parsedFile` (to avoid parsing them again).

This ticket will make `getSimpleJson` return an array containing the data for ***all*** Modelica classes used by the Modelica file:

- including classes that are not actually parsed during the current invocation,
- without duplicate.

The current `parsedFile` array can then simply be created by fetching all `fullMoFilePath` properties from `getSimpleJson()` output.

**Comment by anandkp92** [comment]
Returning the json object is something that we have discussed and its in the plan of implementation. However, we write files to disk because outputs like semantic, require reading multiple json files at the same time and putting them together.

**Comment by AntoineGautier** [comment]
This FE will be implemented in the branch `issue233_returnObject`.

**Comment by AntoineGautier** [comment]
Closed with #234
