### ISSUE TITLE
Check correctness of JSON schema

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-json#237]
Parsing a block from MBL using commit `648b390` of modelica-json creates a JSON file with the following structure.

<img width="586" alt="image" src="https://github.com/user-attachments/assets/cf852fad-8420-4a01-86d3-d63427e9f1a5">

In contrast, the MLS defines `composition` as follows:
```
composition :
   element-list
   { public element-list
     | protected element-list
     | equation-section
     | algorithm-section
   }
   [ external [ language-specification ]
     [ external-function-call ] [ annotation-clause ] ";"
   ]
   [ annotation-clause ";" ]
```
And `element` as follows:
```
element :
   import-clause
   | extends-clause
   | [ redeclare ]
     [ final ]
     [ inner ] [ outer ]
     ( class-definition
       | component-clause
       | replaceable ( class-definition | component-clause )
         [ constraining-clause description ]
     )
```

This brings the following observations.

1. `element_sections` does not exist in the grammar: why is it used in the schema?
2. `equation_section` should not be nested under `element_sections` but directly under `composition` (an equation is not an element). The same observation holds for `algorithm_section` when it is present.
3. Why have `protected_element_list` at a deeper level than `element-list`? Both should be directly nested under `composition`. The same observation holds for `public_element_list` when it is present.

**Comment by AntoineGautier** [comment]
@JayHuLBL Can you look into that?

**Comment by JayHuLBL** [comment]
@AntoineGautier 
With the extra level of `element_sections`, we would potentially keep the element orders. As in the code, we may have sections like:
```
    [element]
    [element]

protected
    [element]
    [element]

public
    [element]
    [element]
```

When parsing it, we can have
```
   [element-list]
   element_sections: [
        {
            "protected_element_list": ...
        },
       {
            "public_element_list": ...
        }
   ]
```

Overall, the major intention is to keep the element order, as it appears in the code. The same reason for the equation sections.

**Comment by AntoineGautier** [comment]
Discussing with @JayHuLBL on 8/9 we agree that the structure proposed above (https://github.com/lbl-srg/modelica-json/issues/237#issuecomment-2275196719) would be the best fit to the Modelica grammar. However, the refactoring appears significant. We'll close this issue for now as it isn't a development priority.
