### ISSUE TITLE
wrong quotation in defaultComponentName

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-json#24]
Parsing `HydraulicDiameter.mo` from commit https://github.com/ibpsa/modelica-ibpsa/commit/537566bf69014ad27739ede40162e58f82bfc4f8
gives the following wrong quotation in the json output:
```
                          {
                            "name": "defaultComponentName",
                            "value": "\"duc"
                          },
```
It looks like moParser.jar parses the entry incorrectly.

**Comment by JayHuLBL** [comment]
@mwetter Thanks for the catch. I will fix it soon.
