### ISSUE TITLE
Enable parser to do the boolean calculation

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-json#58]
Add functionalities:
- [ ] some blocks would be conditionally removed based on Boolean expression results. The parser should be able to calculate the expression and remove the block when the result is false.
- [ ] when a block is conditionally removed, connections to the block should also be removed when parsing the whole class.

Also, check:
- [ ] parser to evaluate the expressions in parameter settings

**Comment by anandkp92** [comment]
Will be handled as part of another issue #102.
