### ISSUE TITLE
html generation for Modelica is incomplete

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-json#60]
The following command does not produce the expected result:
```
rm -rf html
node app.js -f Buildings/Examples/Tutorial/SpaceCooling -o html -m modelica
```

The file `html/Buildings.Examples.Tutorial.html` has an empty `<body>` and the Modelica schematics is not rendered.

**Comment by JayHuLBL** [comment]
The `Buildings.Examples.Tutorial.html` should not be generated. 
This has been addressed in PR #100.
