### ISSUE TITLE
Parse a single Modelica file in modelica parsing mode

### ISSUE THREAD

**Issue by LisaRivalin** [lbl-srg/modelica-json#91]
Add the possibility to parse a single Modelica file. For the moment, only libraries can be translated.

**Comment by JayHuLBL** [comment]
This issue intends to update the parsing in modelica mode. Currently, in modelica parsing mode, it can only parse package, rather than a single Modelica file.

**Comment by anandkp92** [comment]
completed with [v1.0.0](https://github.com/lbl-srg/modelica-json/tree/v1.0.0)
